### ISSUE TITLE
Error 500 with null web-pages links 

### ISSUE THREAD

**Issue by marceloboeira** [jaimeiniesta/metainspectordemo#1]
Just open the page and click at "Scrape"

**Comment by jaimeiniesta** [comment]
Thanks for the warning!

The form uses an input of type URL to check that, but it looks like your browser doesn't implement that.

Anyway, this is just a quick demo. Do you want to submit a pull request to add a validation?

**Comment by jaimeiniesta** [comment]
@marceloboeira that's fixed, can you verify it's working for you now? Thanks!

**Comment by marceloboeira** [comment]
@jaimeiniesta I'm using Safari 8, let me check ...
