### ISSUE TITLE
uninitialized constant MetaInspector::Error

### ISSUE THREAD

**Issue by MECU** [jaimeiniesta/metainspectordemo#16]
```
/home/mecu/code/metainspectordemo/main.rb:43:in `<top (required)>': uninitialized constant MetaInspector::Error (NameError)
Did you mean?  IOError
               Errno
```

I'm running Ruby 2.7.5 and bundler 2.2.32. I did a `bundle install` successfully. I then ran `bundle exec rackup` per the docs and received this error.

**Comment by jaimeiniesta** [comment]
Thanks for your feedback!

This is an old demo that is planned to be archived, but I'll be happy to review a pull request if anyone wants to keep the demo alive.
