### ISSUE TITLE
Update Ruby

### ISSUE THREAD

**Issue by MECU** [jaimeiniesta/metainspectordemo#17]
Ruby v2.7.5 is outdated. Please update Ruby to a newer version.

**Comment by jaimeiniesta** [comment]
Thanks for your feedback!

This is an old demo that is planned to be archived, but I'll be happy to review a pull request if anyone wants to keep the demo alive.

**Comment by jaimeiniesta** [comment]
MetaInspector is tested with Ruby 2.6, 2.7, 3.0, 3.1 and 3.2, see https://app.circleci.com/pipelines/github/metainspector/metainspector
