### ISSUE TITLE
Cookiewall

### ISSUE THREAD

**Issue by asjer** [jaimeiniesta/metainspectordemo#4]
When trying to scrape a website with a cookiewall, the only meta data being returned is from the cookie message. Checkout this [example](https://metainspectordemo.herokuapp.com/scrape?url=http%3A%2F%2Fwww.ad.nl%2Fbinnenland%2Fgeert-wilders-na-dbb-lek-onzin-dat-ik-veilig-ben~aeff1011%2F).

This doesn't seem to be an issue with the [FB OG debugger](https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fwww.ad.nl%2Fbinnenland%2Fgeert-wilders-na-dbb-lek-onzin-dat-ik-veilig-ben~aeff1011%2F).

**Comment by jaimeiniesta** [comment]
Related: #5 

There's not much we can do here, the remote server is deciding it needs to show a cookie consent message, and redirects there.

We're open for PRs if you can think of a generic fix for this situation. Please use the main repo for that:

https://github.com/metainspector/metainspector

Thanks!
